#!/bin/bash
if [ ! -f composer.json ]; then
    composer init --require-dev robmorgan/phinx:0.12.7 --require-dev latte/latte:2.10.3 --autoload 'app/';
    vendor/bin/phinx init;
    cp .env.example.ini .env.ini;
fi
if [ ! -d .cache ]; then
    mkdir .cache;
    chmod -R 0777 .cache;
fi
if [ ! -d db ]; then
    mkdir -p db/migrations db/seeds;
fi