#!/bin/bash
if [ ! -f composer.json ]; then
    composer init --require-dev robmorgan/phinx:0.12.7 --require-dev latte/latte:2.10.3 --autoload 'app/lib/';
    vendor/bin/phinx init;
    cp .env.example.ini .env.ini;
    INSECURE='INSECURE_VXiXWG1NRbQD6YwLeKQfUqZq4ApA20PgFVcrsljhpOEc8PbTKeUjQFW';
    SALT=`tr -dc 0-9A-Za-z </dev/urandom | head -c 64`;
    sed -i "s/$INSECURE/$SALT/" .env.ini;
fi
if [ ! -d .cache ]; then
    mkdir .cache;
    chmod -R 0777 .cache;
fi
if [ ! -d db ]; then
    mkdir -p db/migrations db/seeds;
fi